sudo: true
language: scala

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - oraclejdk7
  - oraclejdk8

matrix:
  include:
  - scala: 2.12.0-RC2
    jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

install:
  - pip install --user codecov

script:
  - if [[ "$TRAVIS_SCALA_VERSION" == 2.11.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION hygiene/compile;
      sbt ++$TRAVIS_SCALA_VERSION spray/test;
      sbt ++$TRAVIS_SCALA_VERSION benchmark/test;
    else echo "Skipping hygiene, spray, and benchmark tests on 2.10 and 2.12";
    fi
  - if [[ "$TRAVIS_BRANCH" == "scalajs" ]];
    then sbt ++$TRAVIS_SCALA_VERSION clean validateJS;
    else
      sbt ++$TRAVIS_SCALA_VERSION clean coverage validateJVM &&
      sbt ++$TRAVIS_SCALA_VERSION coverageReport && codecov;
    fi

  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
